In [1]:
import pandas as pd
import re
import numpy as np

In [2]:
enron = pd.read_csv('C:\\Users\\User\\Desktop\\IronHack\\CLASS\\REGEX ADVANCE\\enron.csv')
enron.head()

                                         raw message
0  From: 40enron@enron.com To:  Subject: 2001 Cha...
1  From: chairman.office@enron.com To:  Subject: ...
2  From: 40enron@enron.com To:  Subject: 2001 Tex...
3  From: kim.clark@enron.com To: croozin@wireweb....
4  From: forster@enron.com To: jeff.skilling@enro...

In [3]:
test=enron['raw message'][1]

In [4]:
enron.shape

(100, 1)

In [5]:
test

"From: chairman.office@enron.com To:  Subject: 2001 Chairman's Award Deadline Extension Cc:  Bcc:  Date: Tue, 9 Oct 2001 20:12:52 -0700 (PDT) body: \nMany of you have requested more time in which to submit your nominations for the 2001 Chairman's Award. In response to your requests, the deadline has been extended to Friday, October 12.Please take this extended opportunity to nominate that special individual who is your everyday hero and a role model who exemplifies Enron's core values of Respect, Integrity, Communication and Excellence.This award represents how important Enron's core values are to the company. The success of this award program is determined by Enron's most valuable asset, you, the employee. Employees at any level can nominate fellow employees from anywhere within the Enron family - from the top down or the bottom up. All of those employees who have been nominated in the past are eligible to be nominated again this year and there is no limit to the number of nominations you may submit. Simply complete a nomination form and submit it by Friday, October 12, 2001. Forms can be obtained by visiting your intranet site or at home.enron.com and in Houston they are available in the elevator lobbies. In addition, this year we have a new way you can nominate that everyday Enron hero. Simply pick up the phone and dial 713-345-2492, follow the simple and quick instructions and leave your nomination by phone.The finalists for the award, the Chairman's Roundtable, and the Chairman's Award winner will be honored at Enron's Management Conference in San Antonio on November 15.Thank you for your participation.\n"

In [6]:
re.findall('From: [\w\@\.-_]+ ',test)

['From: chairman.office@enron.com ']

In [7]:
def get_sender(message):
    return re.findall('From: [\w\@\.-_]+ ',test)
enron['From'] = enron['raw message'].apply(get_sender)
enron

,raw message,From
0,From: 40enron@enron.com To: Subject: 2001 Cha...,[From: chairman.office@enron.com ]
1,From: chairman.office@enron.com To: Subject: ...,[From: chairman.office@enron.com ]
2,From: 40enron@enron.com To: Subject: 2001 Tex...,[From: chairman.office@enron.com ]
3,From: kim.clark@enron.com To: croozin@wireweb....,[From: chairman.office@enron.com ]
4,From: forster@enron.com To: jeff.skilling@enro...,[From: chairman.office@enron.com ]
...,...,...
95,From: clay@dfj.com To: lou.pai@enron.com Subje...,[From: chairman.office@enron.com ]
96,From: sdsl768k@yahoo.com To: jskilli@enron.com...,[From: chairman.office@enron.com ]
97,From: mrudula.gadade@enron.com To: kenneth.lay...,[From: chairman.office@enron.com ]
98,From: hemery@firstunion1.com To: Subject: Dai...,[From: chairman.office@enron.com ]
99,From: no.address@enron.com To: Subject: Daily...,[From: chairman.office@enron.com ]

In [8]:
def get_sender(message):
    li = re.findall('From: [\w\@\.-]+ ',test)
    
    return li[0]

enron

,raw message,From
0,From: 40enron@enron.com To: Subject: 2001 Cha...,[From: chairman.office@enron.com ]
1,From: chairman.office@enron.com To: Subject: ...,[From: chairman.office@enron.com ]
2,From: 40enron@enron.com To: Subject: 2001 Tex...,[From: chairman.office@enron.com ]
3,From: kim.clark@enron.com To: croozin@wireweb....,[From: chairman.office@enron.com ]
4,From: forster@enron.com To: jeff.skilling@enro...,[From: chairman.office@enron.com ]
...,...,...
95,From: clay@dfj.com To: lou.pai@enron.com Subje...,[From: chairman.office@enron.com ]
96,From: sdsl768k@yahoo.com To: jskilli@enron.com...,[From: chairman.office@enron.com ]
97,From: mrudula.gadade@enron.com To: kenneth.lay...,[From: chairman.office@enron.com ]
98,From: hemery@firstunion1.com To: Subject: Dai...,[From: chairman.office@enron.com ]
99,From: no.address@enron.com To: Subject: Daily...,[From: chairman.office@enron.com ]

In [9]:
re.findall('(From: )([\w\@\.-]+)',test)[0][1]

'chairman.office@enron.com'

In [10]:
def get_sender(message): 
    return re.findall('(From: )([\w\@\.-]+)( )',message)[0][1]

enron['From'] = enron['raw message'].apply(get_sender)
enron

,raw message,From
0,From: 40enron@enron.com To: Subject: 2001 Cha...,40enron@enron.com
1,From: chairman.office@enron.com To: Subject: ...,chairman.office@enron.com
2,From: 40enron@enron.com To: Subject: 2001 Tex...,40enron@enron.com
3,From: kim.clark@enron.com To: croozin@wireweb....,kim.clark@enron.com
4,From: forster@enron.com To: jeff.skilling@enro...,forster@enron.com
...,...,...
95,From: clay@dfj.com To: lou.pai@enron.com Subje...,clay@dfj.com
96,From: sdsl768k@yahoo.com To: jskilli@enron.com...,sdsl768k@yahoo.com
97,From: mrudula.gadade@enron.com To: kenneth.lay...,mrudula.gadade@enron.com
98,From: hemery@firstunion1.com To: Subject: Dai...,hemery@firstunion1.com
99,From: no.address@enron.com To: Subject: Daily...,no.address@enron.com

In [11]:
test=enron['raw message'][3]
test

'From: kim.clark@enron.com To: croozin@wireweb.net, richard-zapalac@reliantenergy.com,pdifonzo@nbutexas.com, meek@nbcham.org, kmayfiel@enron.com, \r\nkathleen.devine@usaa.com, joe.guinn@phs.com, jpfeuffer@aol.com, \r\njldavis@txi.com, em1832@txmail.sbc.com, h2omiller@aol.com, \r\ndennis.heit Subject: 2002 Texan of the Year Cc:  Bcc:  Date: Fri, 11 May 2001 13:50:00 -0700 (PDT) body: \nPlease respond to Kim Clark   - Bush Ballot.doc \n'

In [12]:
re.findall('(To: )([\w\@\.-]+)( )',test)

[]

In [13]:
def reciver(message):
    if len(re.findall('(To: )([\w\@\.-]+)( )',message))>0:
        return re.findall('(To: )([\w\@\.-]+)( )',message)[0][1]
    else:
        return np.nan

In [14]:
enron['To'] = enron['raw message'].apply(reciver)
enron.head(10)

,raw message,From,To
0,From: 40enron@enron.com To: Subject: 2001 Cha...,40enron@enron.com,NaN
1,From: chairman.office@enron.com To: Subject: ...,chairman.office@enron.com,NaN
2,From: 40enron@enron.com To: Subject: 2001 Tex...,40enron@enron.com,NaN
3,From: kim.clark@enron.com To: croozin@wireweb....,kim.clark@enron.com,NaN
4,From: forster@enron.com To: jeff.skilling@enro...,forster@enron.com,jeff.skilling@enron.com
5,From: rnstnhgn@earthlink.net To: houston_membe...,rnstnhgn@earthlink.net,houston_members@ypo.org
6,From: stephanie.strong@enron.com To: Subject:...,stephanie.strong@enron.com,NaN
7,From: adarsh.vakharia@enron.com To: rick.buy@e...,adarsh.vakharia@enron.com,NaN
8,From: dottie@kerr-solutions.com To: Subject: ...,dottie@kerr-solutions.com,NaN
9,From: dottie.kerr@enron.com To: Subject: ACG ...,dottie.kerr@enron.com,NaN

In [15]:
test2 =test=enron['raw message'][3]
test

'From: kim.clark@enron.com To: croozin@wireweb.net, richard-zapalac@reliantenergy.com,pdifonzo@nbutexas.com, meek@nbcham.org, kmayfiel@enron.com, \r\nkathleen.devine@usaa.com, joe.guinn@phs.com, jpfeuffer@aol.com, \r\njldavis@txi.com, em1832@txmail.sbc.com, h2omiller@aol.com, \r\ndennis.heit Subject: 2002 Texan of the Year Cc:  Bcc:  Date: Fri, 11 May 2001 13:50:00 -0700 (PDT) body: \nPlease respond to Kim Clark   - Bush Ballot.doc \n'

In [16]:
#crazy

re.findall("(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|'(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*')@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])", test2)

['kim.clark@enron.com',
 'croozin@wireweb.net',
 'richard-zapalac@reliantenergy.com',
 'pdifonzo@nbutexas.com',
 'meek@nbcham.org',
 'kmayfiel@enron.com',
 'kathleen.devine@usaa.com',
 'joe.guinn@phs.com',
 'jpfeuffer@aol.com',
 'jldavis@txi.com',
 'em1832@txmail.sbc.com',
 'h2omiller@aol.com']

In [17]:
test3 =test=enron['raw message'][3]
test3

'From: kim.clark@enron.com To: croozin@wireweb.net, richard-zapalac@reliantenergy.com,pdifonzo@nbutexas.com, meek@nbcham.org, kmayfiel@enron.com, \r\nkathleen.devine@usaa.com, joe.guinn@phs.com, jpfeuffer@aol.com, \r\njldavis@txi.com, em1832@txmail.sbc.com, h2omiller@aol.com, \r\ndennis.heit Subject: 2002 Texan of the Year Cc:  Bcc:  Date: Fri, 11 May 2001 13:50:00 -0700 (PDT) body: \nPlease respond to Kim Clark   - Bush Ballot.doc \n'

In [18]:
#my try

re.findall('(Date: )(\w{3}.\W+\d+\W\w{3})',test3)

[('Date: ', 'Fri, 11 May')]

In [19]:
#teacher try

re.findall('(Date: \w{3}, )(\d{1,2} \w{3} \d{4})', test3)[0][1]

'11 May 2001'

In [20]:
def get_date(message): 
    return re.findall('(Date: \w{3}, )(\d{1,2} \w{3} \d{4})', message)[0][1]

enron['date'] = enron['raw message'].apply(get_date)
enron

,raw message,From,To,date
0,From: 40enron@enron.com To: Subject: 2001 Cha...,40enron@enron.com,NaN,16 Sep 2001
1,From: chairman.office@enron.com To: Subject: ...,chairman.office@enron.com,NaN,9 Oct 2001
2,From: 40enron@enron.com To: Subject: 2001 Tex...,40enron@enron.com,NaN,23 Sep 2001
3,From: kim.clark@enron.com To: croozin@wireweb....,kim.clark@enron.com,NaN,11 May 2001
4,From: forster@enron.com To: jeff.skilling@enro...,forster@enron.com,jeff.skilling@enron.com,4 Jun 2001
...,...,...,...,...
95,From: clay@dfj.com To: lou.pai@enron.com Subje...,clay@dfj.com,lou.pai@enron.com,31 May 2001
96,From: sdsl768k@yahoo.com To: jskilli@enron.com...,sdsl768k@yahoo.com,jskilli@enron.com,7 Nov 2001
97,From: mrudula.gadade@enron.com To: kenneth.lay...,mrudula.gadade@enron.com,NaN,15 May 2001
98,From: hemery@firstunion1.com To: Subject: Dai...,hemery@firstunion1.com,NaN,19 Jul 2001
99,From: no.address@enron.com To: Subject: Daily...,no.address@enron.com,NaN,1 Nov 2001

In [21]:
test

'From: kim.clark@enron.com To: croozin@wireweb.net, richard-zapalac@reliantenergy.com,pdifonzo@nbutexas.com, meek@nbcham.org, kmayfiel@enron.com, \r\nkathleen.devine@usaa.com, joe.guinn@phs.com, jpfeuffer@aol.com, \r\njldavis@txi.com, em1832@txmail.sbc.com, h2omiller@aol.com, \r\ndennis.heit Subject: 2002 Texan of the Year Cc:  Bcc:  Date: Fri, 11 May 2001 13:50:00 -0700 (PDT) body: \nPlease respond to Kim Clark   - Bush Ballot.doc \n'

In [22]:
def names_mentioned_narrow_dow(message):
    return re.findall('[A-Z][a-z]+ [A-Z][a-z]+', message)
    
enron['names_mentioned'] = enron['raw message'].apply(names_mentioned_narrow_dow)
enron

,raw message,From,To,date,names_mentioned
0,From: 40enron@enron.com To: Subject: 2001 Cha...,40enron@enron.com,NaN,16 Sep 2001,"[Award Cc, Everyday Heroes, All Enron, Selecti..."
1,From: chairman.office@enron.com To: Subject: ...,chairman.office@enron.com,NaN,9 Oct 2001,"[Award Deadline, Extension Cc, Management Conf..."
2,From: 40enron@enron.com To: Subject: 2001 Tex...,40enron@enron.com,NaN,23 Sep 2001,"[Havoline Grand, Prix Cc, West Racing, Havolin..."
3,From: kim.clark@enron.com To: croozin@wireweb....,kim.clark@enron.com,NaN,11 May 2001,"[Year Cc, Kim Clark, Bush Ballot]"
4,From: forster@enron.com To: jeff.skilling@enro...,forster@enron.com,jeff.skilling@enron.com,4 Jun 2001,"[Floor Meeting, Feedback Cc, Hi Jeff, Houston ..."
...,...,...,...,...,...
95,From: clay@dfj.com To: lou.pai@enron.com Subje...,clay@dfj.com,lou.pai@enron.com,31 May 2001,"[Clay Pew, Special Partner, Draper Fisher, Inf..."
96,From: sdsl768k@yahoo.com To: jskilli@enron.com...,sdsl768k@yahoo.com,jskilli@enron.com,7 Nov 2001,"[Activation Fee, It Can, Be Cheaper, Internet ..."
97,From: mrudula.gadade@enron.com To: kenneth.lay...,mrudula.gadade@enron.com,NaN,15 May 2001,"[Dabhol Taskforce, Dabhol Taskforce]"
98,From: hemery@firstunion1.com To: Subject: Dai...,hemery@firstunion1.com,NaN,19 Jul 2001,"[Daily Research, The First, Union Securities, ..."
99,From: no.address@enron.com To: Subject: Daily...,no.address@enron.com,NaN,1 Nov 2001,"[Daily Update, Morgan Chase, Salomon Smith, Ci..."

In [23]:
enron.iloc[1]['raw message']

"From: chairman.office@enron.com To:  Subject: 2001 Chairman's Award Deadline Extension Cc:  Bcc:  Date: Tue, 9 Oct 2001 20:12:52 -0700 (PDT) body: \nMany of you have requested more time in which to submit your nominations for the 2001 Chairman's Award. In response to your requests, the deadline has been extended to Friday, October 12.Please take this extended opportunity to nominate that special individual who is your everyday hero and a role model who exemplifies Enron's core values of Respect, Integrity, Communication and Excellence.This award represents how important Enron's core values are to the company. The success of this award program is determined by Enron's most valuable asset, you, the employee. Employees at any level can nominate fellow employees from anywhere within the Enron family - from the top down or the bottom up. All of those employees who have been nominated in the past are eligible to be nominated again this year and there is no limit to the number of nominations you may submit. Simply complete a nomination form and submit it by Friday, October 12, 2001. Forms can be obtained by visiting your intranet site or at home.enron.com and in Houston they are available in the elevator lobbies. In addition, this year we have a new way you can nominate that everyday Enron hero. Simply pick up the phone and dial 713-345-2492, follow the simple and quick instructions and leave your nomination by phone.The finalists for the award, the Chairman's Roundtable, and the Chairman's Award winner will be honored at Enron's Management Conference in San Antonio on November 15.Thank you for your participation.\n"

In [41]:
def phone_number(message):
    return re.findall('[0-9]{3}-[0-9]{3}-[0-9]{4}', message)
    
enron['PHONE NUMBER'] = enron['raw message'].apply(phone_number)
enron

,raw message,From,To,date,names_mentioned,PHONE NUMBER
0,From: 40enron@enron.com To: Subject: 2001 Cha...,40enron@enron.com,NaN,16 Sep 2001,"[Award Cc, Everyday Heroes, All Enron, Selecti...",[]
1,From: chairman.office@enron.com To: Subject: ...,chairman.office@enron.com,NaN,9 Oct 2001,"[Award Deadline, Extension Cc, Management Conf...",[713-345-2492]
2,From: 40enron@enron.com To: Subject: 2001 Tex...,40enron@enron.com,NaN,23 Sep 2001,"[Havoline Grand, Prix Cc, West Racing, Havolin...",[]
3,From: kim.clark@enron.com To: croozin@wireweb....,kim.clark@enron.com,NaN,11 May 2001,"[Year Cc, Kim Clark, Bush Ballot]",[]
4,From: forster@enron.com To: jeff.skilling@enro...,forster@enron.com,jeff.skilling@enron.com,4 Jun 2001,"[Floor Meeting, Feedback Cc, Hi Jeff, Houston ...",[]
...,...,...,...,...,...,...
95,From: clay@dfj.com To: lou.pai@enron.com Subje...,clay@dfj.com,lou.pai@enron.com,31 May 2001,"[Clay Pew, Special Partner, Draper Fisher, Inf...",[]
96,From: sdsl768k@yahoo.com To: jskilli@enron.com...,sdsl768k@yahoo.com,jskilli@enron.com,7 Nov 2001,"[Activation Fee, It Can, Be Cheaper, Internet ...",[]
97,From: mrudula.gadade@enron.com To: kenneth.lay...,mrudula.gadade@enron.com,NaN,15 May 2001,"[Dabhol Taskforce, Dabhol Taskforce]","[800-991-9019, 847-619-8039]"
98,From: hemery@firstunion1.com To: Subject: Dai...,hemery@firstunion1.com,NaN,19 Jul 2001,"[Daily Research, The First, Union Securities, ...",[]
99,From: no.address@enron.com To: Subject: Daily...,no.address@enron.com,NaN,1 Nov 2001,"[Daily Update, Morgan Chase, Salomon Smith, Ci...",[]